package com.louie.ssm.model;

import java.util.Date;

public class TUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.USER_NAME
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.USER_PHONE
     *
     * @mbg.generated
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.USER_EMAIL
     *
     * @mbg.generated
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.USER_PWD
     *
     * @mbg.generated
     */
    private String userPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.PWD_SALT
     *
     * @mbg.generated
     */
    private String pwdSalt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.MODIFY_TIME
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.IS_DELETE
     *
     * @mbg.generated
     */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbg.generated
     */
    public TUser(Long id, String userName, String userPhone, String userEmail, String userPwd, String pwdSalt, Date createTime, Date modifyTime, Byte isDelete) {
        this.id = id;
        this.userName = userName;
        this.userPhone = userPhone;
        this.userEmail = userEmail;
        this.userPwd = userPwd;
        this.pwdSalt = pwdSalt;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.ID
     *
     * @return the value of T_USER.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.USER_NAME
     *
     * @return the value of T_USER.USER_NAME
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.USER_PHONE
     *
     * @return the value of T_USER.USER_PHONE
     *
     * @mbg.generated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.USER_EMAIL
     *
     * @return the value of T_USER.USER_EMAIL
     *
     * @mbg.generated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.USER_PWD
     *
     * @return the value of T_USER.USER_PWD
     *
     * @mbg.generated
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.PWD_SALT
     *
     * @return the value of T_USER.PWD_SALT
     *
     * @mbg.generated
     */
    public String getPwdSalt() {
        return pwdSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.CREATE_TIME
     *
     * @return the value of T_USER.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.MODIFY_TIME
     *
     * @return the value of T_USER.MODIFY_TIME
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.IS_DELETE
     *
     * @return the value of T_USER.IS_DELETE
     *
     * @mbg.generated
     */
    public Byte getIsDelete() {
        return isDelete;
    }
}